name: Rustvn.com deployer

on:
  push:
  push:
    branches: [ master ]

jobs:
  deploy-blog:
    name: Deploy blog to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.16.1/zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz
      - name: Build site
        run: ./zola build
      - name: Deploy site to S3
        run: |
          aws s3 sync ./public s3://rustvn-wiki
         
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1